/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hrank.basics;

import org.junit.Test;
import static org.junit.Assert.*;

public class MilitaryTimeTest {
    @Test public void testAfterMidnight() {
        assertEquals("should set 12 to 00", "00:01:00", MilitaryTime.convertStringToMilitaryTime("12:01:00AM"));
    }

    @Test public void testMorning() {
        assertEquals("should retain original format", "08:11:00", MilitaryTime.convertStringToMilitaryTime("08:11:00AM"));
        assertEquals("should retain original format", "11:15:00", MilitaryTime.convertStringToMilitaryTime("11:15:00AM"));
    }

    @Test public void testAfternoon() {
        assertEquals("should retain original format", "12:35:00", MilitaryTime.convertStringToMilitaryTime("12:35:00PM"));
    }

    @Test public void testEvening() {
        assertEquals("should retain original format", "15:01:00", MilitaryTime.convertStringToMilitaryTime("03:01:00PM"));
        assertEquals("should retain original format", "23:20:00", MilitaryTime.convertStringToMilitaryTime("11:20:00PM"));
    }
}
