/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hrank.basics;

public class MilitaryTime {
    public static String convertStringToMilitaryTime(String standardTime) {
        if (standardTime.charAt(standardTime.length() - 2) == 'A') {
            if (Integer.parseInt(standardTime.substring(0, 2)) == 12) {
                return ("00" + standardTime.substring(2, 8));
            }
            return standardTime.substring(0, 8);
        }
        if (Integer.parseInt(standardTime.substring(0, 2)) == 12) {
            return standardTime.substring(0, 8);
        }
        return (Integer.parseInt(standardTime.substring(0, 2)) + 12) + standardTime.substring(2, 8);
    }
}
